version: '3'
services:
  node-1:
    image: not-raft:latest
    ports:
      - "8000:8000"
    environment:
      - NODE_ID=a
      - NODE_PEERS=node-2:8001,node-3:8001
  node-2:
    image: not-raft:latest
    environment:
      - NODE_ID=b
      - NODE_PEERS=node-1:8001,node-3:8001
  node-3:
    image: not-raft:latest
    environment:
      - NODE_ID=c
      - NODE_PEERS=node-1:8001,node-2:8001
